export { WorkspaceService } from './workspace'
export { VaultService } from './vaults'
export { FsTreeService } from './fsTree'
export { TrashService } from './trash'
export { FavoritesService, RecentsService } from './favorites'
export { SettingsService } from './settings'
export { AccountService } from './account'
export { GithubService } from './github'
export { GitService } from './gitService'
export { WatcherService } from './watcher'
export { PluginHost } from './pluginHost'
export type { PluginInfo } from '@shared/types'
